name: gist
author: Kasper Peulen <kasperpeulen@gmail.com>
description: |
  Create and edit gist from the command line.
version: 0.0.1
environment:
  sdk: '>=1.12.0-dev.4.0 <2.0.0'
executables:
  gist:
dependencies:
  args: '^0.13.2'
  github:
    git:
      url: https://github.com/kasperpeulen/github.dart.git
      ref: editGist2
  yaml: '^2.1.3'
  prompt: '^0.1.7'
  analyzer: '^0.26.0'
  path: '^1.3.6'
